
- name: Ensure the destination directory exists
  file:
    path: /root/Ansible
    state: directory
    mode: '0755'

- name: Copy application files
  copy:
    src: /home/sweetyj/Ansibleteamproject/Application/NodeJS_app/server.js
    dest: /root/Ansible
    owner: root
    group: root
    mode: '0644'      
